server:
  port: 8080
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    id: ${spring.application.name}:${spring.application.instance_id}:${random.value}
spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: ms-account-transactions
          uri: lb://ms-account-transactions
          predicates:
            - Path=/account/transactions
          filters:
            - StripPrefix=2


