logging:
    level:
        org:
            springframework:
                data:
                    mongodb:
                        core:
                            ReactiveMongoTemplate: DEBUG
        root: info
    pattern:
        console: '%d{dd-MM-yyyy HH:mm:ss.SSS} %magenta([%thread]) %highlight(%-5level)
            %logger.%M - %msg%n'
spring:
    data:
        mongodb:
            uri: mongodb+srv://rcastillo:KCou0pjmj5C6iItL@cluster0.xplzl.mongodb.net/Cluster0?retryWrites=true&w=majority

eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service:
      url:
        defaultZone: http://localhost:8761/eureka
  instance:
    id: ${spring.application.name}:${spring.application.instance_id}:${random.value}

server:
  port: ${PORT:0}

management:
  endpoints:
    web:
      exposure:
        include: *